name: Build & Publish Nuget

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      working-directory: ./DemoMomo/DemoMomo
      run: dotnet restore
      
    - name: Build
      working-directory: ./DemoMomo/DemoMomo
      run: dotnet build --no-restore --configuration Release
      
    - name: Pack
      working-directory: ./DemoMomo/DemoMomo
      run: dotnet pack --no-build --configuration Release -o ../../Nugets
      
    - name: Debug
      working-directory: ./Nugets
      run: echo dotnet nuget push "*.nupkg" -k $REPO-TOKEN -s https://nuget.pkg.github.com/ErezG/index.json
      env:
        REPO-TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Push package
      working-directory: ./Nugets
      run: dotnet nuget push "*.nupkg" -k $REPO-TOKEN -s https://nuget.pkg.github.com/ErezG/index.json
      env:
        REPO-TOKEN: ${{ secrets.GITHUB_TOKEN }}
