name: Build & Publish Nuget

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Bump_Version:

    runs-on: ubuntu-latest
    env:
      CURRENT_VERSION:

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Get existing version
      working-directory: ./DemoMomo/DemoMomo
      run: |
        CURRENT_VERSION=$(sed -e 's/[<]AssemblyVersion[>]\([0-9.]\+\)[<][/]AssemblyVersion[>]/\1/' DemoMomo.csproj)
        echo CURRENT_VERSION: $CURRENT_VERSION
      
    - name: Choose version bump
      run: bump_type='MINOR'
      
    - name: Create new version
      run: |
        echo CURRENT_VERSION: $CURRENT_VERSION
        [[ "$CURRENT_VERSION" =~ ([0-9]+).([0-9]+).([0-9]+)$ ]] && major="${BASH_REMATCH[1]}" && minor="${BASH_REMATCH[2]}" && patch="${BASH_REMATCH[3]}";
        case $bump_type in
          MAJOR)
            major=$(($major + 1))
        	;;
          MINOR)
            minor=$(($minor + 1))
        	;;
          *)
            patch=$(($patch + 1))
        	;;
        esac
        new_version=$major.$minor.$patch
        echo new_version: $new_version
      
    - name: Update version
      working-directory: ./DemoMomo/DemoMomo
      run: sed -r s#\<AssemblyVersion\>[0-9.]+\<\/AssemblyVersion\>#\<AssemblyVersion\>$new_version\<\/AssemblyVersion\>#g DemoMomo.csproj
      
    - name: Commit new version
      run: |
        git stage */DemoMomo.csproj
        git status
        #git_message=(v$current_version' => 'v$new_version)
        #git commit -m $git_message
        #git push
      
  #Pack_and_Push:
  #
  #  runs-on: ubuntu-latest
  #
  #  steps:
  #  
  #  - name: Checkout
  #    uses: actions/checkout@v2
  #  
  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v1
  #    with:
  #      dotnet-version: 3.1.x
  #      
  #  - name: Restore dependencies
  #    working-directory: ./DemoMomo/DemoMomo
  #    run: dotnet restore
  #    
  #  - name: Build
  #    working-directory: ./DemoMomo/DemoMomo
  #    run: dotnet build --no-restore --configuration Release
  #    
  #  - name: Pack
  #    working-directory: ./DemoMomo/DemoMomo
  #    run: dotnet pack --no-build --configuration Release -o ../../Nugets
  #    
  #  - name: Push package
  #    working-directory: ./Nugets
  #    run: dotnet nuget push "*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/ErezG/index.json
